---
on:
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    - cron: '0 0 * * 0'

name: Automatic Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate documentation
        run: |
          yarn run docs:build
          git add --all
          git commit -m "docs: update documentation"

      - name: Prerelease
        run: |
          yarn run release
          git push origin master
