name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set npm token
        run: npm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package with next tag when prereleased
        if: github.event.release.prerelease
        run: npm publish --tag next
      
      - name: Publish package with latest tag when released
        if: github.event.release.prerelease != true
        run: npm publish
